name: "ghctl"
description: "GitHub Action for ghctl"
inputs:
  args:
    description: >-
      Program arguments
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: gitsudo-io/ghctl
        file: ghctl
        version: tags/v0.1.1
        target: /usr/local/bin/ghctl
    - shell: bash
      run: |
        ghctl ${{ inputs.args }}
