name: "ghctl"
description: "GitHub Action for ghctl"
inputs:
  args:
    description: >-
      Program arguments
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: gitsudo-io/ghctl
        version: tags/v0.1.0
        file: ghctl
        target: /usr/local/bin/ghctl
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - shell: bash
      run: |
        cargo build --release
        mv target/release/ghctl /usr/local/bin/ghctl
        ghctl ${{ inputs.args }}
