name: "ghctl"
description: "GitHub Action for ghctl"
inputs:
  args:
    description: >-
      Program arguments
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: gitsudo-io/ghctl
        file: ghctl-x86_64-unknown-linux-gnu.tar.gz
        target: ghctl-x86_64-unknown-linux-gnu.tar.gz
    - shell: bash
      run: |
        tar -xzf ghctl-x86_64-unknown-linux-gnu.tar.gz
        mv ghctl /usr/local/bin/ghctl
        chmod +x /usr/local/bin/ghctl
        ghctl ${{ inputs.args }}
