name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        target: 
          - aarch64-unknown-linux-gnu
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          cargo test
          cargo clippy
          cargo build --release --target ${{ matrix.target }}
          cd target/${{ matrix.target }}/release          
          tar czvf ../../../ghctl-${{ matrix.target }}.tar.gz ghctl
          cd -

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            ghctl-${{ matrix.target }}.tar.gz

  cargo-publish:
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: cargo publish
        run: |
          cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}
