name: Test the Action
on: push

jobs:
  ghctl-repo-config-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitsudo-io/ghctl@main
        with:
            args: repo config apply gitsudo/ghctl --access-token ${{ secrets.PERSONAL_ACCESS_TOKEN }} -F test/ghctl.yaml
