name: Tests
on:
  push:
    paths:
      - "src/**"
      - "Cargo.*"
      - "test/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo test
