name: Test the Action
on: 
  push:
    paths-ignore:
      - .github/README.md.erb
      - README.md
      - LICENSE
  workflow_dispatch:    

jobs:
  ghctl-repo-config-apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gitsudo-io/ghctl@main
        with:
            args: version
      - uses: gitsudo-io/ghctl@main
        env:
          RUST_LOG: ghctl=debug
        with:
            args: repo config apply gitsudo-io/ghctl -F test/ghctl.yaml --access-token ${{ secrets.PERSONAL_ACCESS_TOKEN }}
