name: Tests
on:
  push:
    branches:
      - '**'
    paths:
      - "src/**"
      - "Cargo.*"
      - "test/**"
      - "features/**"
      - "Gemfile"
      - "Gemfile.lock"
      - ".ruby*"
      - ".github/workflows/tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo clippy

  cucumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: ruby/setup-ruby@v1
      - name: Cucumber + Aruba tests
        run: |
          bundle install
          cucumber
